language: java
sudo: false
jdk:
- oraclejdk8
after_success:
- '[[ $TRAVIS_BRANCH == "master" ]] && {  mvn -q --settings .travis-settings.xml -DskipTests deploy; };'
env:
  global:
  - secure: 14vy75RA+qF/DAYGXhF7ZXoZz5tG88UoJ6EZCQ0CbyYvgz07VmVJ4/E/D8BXqtUYYVN18EQQpfGp3XMJ3pVtJHZr9YiMslyvj8qOY4s2bMdAKV5XZtWWnOUrk2r/SiTNpz02qnXogHqTKUcOvr6WhELomwkV7oIFQg+95mZgfWZM1mN3HZ3IUua2V2rDRnxEQm3L7Mr+Af/KwaTIyKux+sqzQo3FRm6KN0cFh7NLTmvGqEyq82xWKriUmLjj8pgkNbft1BVN7VouxPxqdf20uQfqmf4OdQ71bi36lpReI4y8va2PCLWkACTFgE/KONE4FpMVDiS+p9T8Fse9W3zDp7XP6sUZd9caz0iZ8jVZ5IAlpMXfvnY55wXKWYhmuxQkDbA5Eq/hXuRILFqWIXDvpLP2QIWjygwro6Y1BgZPNgMs8PmV1Tg6+9JdKYe0EOCVGWaN3sRzXPOLUYQrZAed3fkKfZheiLwQgl6L4r9wTkdxOP1xv4KVWMleYoTCP11Q6Est3Zwv8pzghr9OUlhHDuyRyQ+8zFB6XnFhAoDfutSMj1FqMd4t/vJpFEkBDGJyxMjey/bNakJQMWl4ZPQ/slojtcoSyhQIOkK752+wbYiXhz8kq5LNa3jk22fHZb+a6DRIPaP95sVKWK3AMzpmyUCldws0EvuaS5wHhsu7D0U=
  - secure: lqCmGy6tsyO4URr3umBd6GOvWKGUfyT2FYeD9J6UcemV/DaR0cwGGDYOWQ0FKodAxvG6NYE2bmXpMsksdfwuol1YOzv+DLszngYhRYt2TXU/ZO09iXXWu1AWs30zqTSebOVaHHy1IjQ+65s3x8jAwsGUE80VIH52nr01yxrmvTBWcbZmXyPUNObbIpyAr48XP3rIh4B49TCJ/2RVgdyMbAM0Zg4DXTkjiAl9Lp754j34IvPR7UlbDsPPHutDan8AS/VxoOMbUvGq0WiceHVMSDFfqhnNoFarHVhMB3/cMxO1bl8sb4oJyLPxOoB1HwBC9TdfQmOTORqY9Lkt2NJwV9JT+yV/FCCAnWeYKcaswXWE3i6k7xyeBf/ZpQR9lKrAGwaryiGRPF38uecwJ4/ZmbPCzRpA5FVsWPibLN41eYlD4qakLhazt1/bLq7U2EleR8u4guTMK4yyOOM/uN8G2nZhg5acoHD75RG8omyAVn7xTeJKviNGU8Swhft3ix6saSt8tuVsmprR/4GzqCRAZjfot4kqI+sAmqqpeULROnvnxJ4pSXsQjDWLYOMfh67M3TG++riyxA1LnT62nUZ69jAMy0LoUXjY6pSWaavPB2+DQSa5iBYvd1dhgBjHQNt5vIhi8zU4TJWXr5wAR1odPiBFaNPxieTKdTAXbeRR/vo=
addons:
  apt:
    packages:
      - oracle-java8-installer
